# Generated by Django 5.0.6 on 2024-09-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='foto_orang',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
