# Generated by Django 5.0.6 on 2024-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kavling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode_kavling', models.CharField(max_length=10)),
                ('luas_tanah', models.IntegerField()),
                ('harga_per_meter', models.IntegerField()),
                ('harga_jual_cash', models.IntegerField()),
                ('map_code', models.CharField(max_length=255)),
                ('is_cash', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Tersedia'), (1, 'Booking'), (2, 'Terjual')], default=0)),
            ],
        ),
    ]
