# Generated by Django 5.0.6 on 2024-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0002_remove_kavling_is_cash_alter_kavling_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kavling',
            name='map_code',
            field=models.TextField(),
        ),
    ]
