# Generated by Django 5.0.6 on 2024-06-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0003_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
