# Generated by Django 5.0.6 on 2024-06-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0003_alter_kavling_map_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=50)),
                ('nama_website', models.CharField(max_length=50)),
                ('nama_perusahaan', models.CharField(max_length=50)),
                ('template_kavling', models.TextField()),
            ],
            options={
                'db_table': 'site',
            },
        ),
    ]
