# Generated by Django 5.0.6 on 2024-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0004_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='no_hp',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
