# Generated by Django 5.0.6 on 2024-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0005_site_no_hp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kavling',
            old_name='map_code',
            new_name='map_code_g',
        ),
        migrations.AddField(
            model_name='kavling',
            name='map_code_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
