# Generated by Django 5.0.6 on 2024-06-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kk',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ktp',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
