# Generated by Django 5.0.6 on 2024-06-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0008_transaksi'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaksi',
            table='transaksi',
        ),
    ]
