# Generated by Django 5.0.6 on 2024-06-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0009_alter_transaksi_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='tipe_transaksi',
            field=models.IntegerField(choices=[(0, 'Booking'), (1, 'Cash'), (2, 'Kredit')], default=0),
        ),
    ]
