# Generated by Django 5.0.6 on 2024-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0010_alter_transaksi_tipe_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='is_lunas',
            field=models.IntegerField(null=True),
        ),
    ]
