# Generated by Django 5.0.6 on 2024-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0011_transaksi_is_lunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kavling',
            name='text_code_svg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
