# Generated by Django 5.0.6 on 2024-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0012_kavling_text_code_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kavling',
            name='map_code_g',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kavling',
            name='map_code_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kavling',
            name='text_code_svg',
            field=models.TextField(null=True),
        ),
    ]
