# Generated by Django 5.0.6 on 2024-06-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0013_alter_kavling_map_code_g_alter_kavling_map_code_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kavling',
            name='harga_jual_cash',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kavling',
            name='harga_per_meter',
            field=models.IntegerField(null=True),
        ),
    ]
