# Generated by Django 5.0.6 on 2024-06-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0015_marketing_remove_transaksi_marketing_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marketing',
            table='marketing',
        ),
    ]
