# Generated by Django 5.0.6 on 2024-06-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0016_alter_marketing_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='marketing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backstore.marketing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstore.customer'),
        ),
    ]
