# Generated by Django 5.0.6 on 2024-06-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0017_transaksi_marketing_alter_transaksi_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='is_lunas',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
