# Generated by Django 5.0.6 on 2024-06-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0018_alter_transaksi_is_lunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='alamat',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='no_telp',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='ttd',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
