# Generated by Django 5.0.6 on 2024-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0019_site_alamat_site_email_site_no_telp_site_ttd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
