# Generated by Django 5.0.6 on 2024-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0020_alter_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.FileField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='no_telp',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
