# Generated by Django 5.0.6 on 2024-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0021_alter_site_logo_alter_site_no_telp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
