# Generated by Django 5.0.6 on 2024-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('alamat', models.TextField()),
                ('jk', models.IntegerField(choices=[(0, 'Laki-Laki'), (1, 'Perempuan')], default=0)),
                ('no_hp', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'marketing',
            },
        ),
    ]
