# Generated by Django 5.0.6 on 2024-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kavling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode_kavling', models.CharField(max_length=10)),
                ('luas_tanah', models.IntegerField()),
                ('harga_per_meter', models.IntegerField(null=True)),
                ('harga_jual_cash', models.IntegerField(null=True)),
                ('map_code_g', models.TextField(null=True)),
                ('map_code_path', models.TextField(null=True)),
                ('text_code_svg', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Tersedia'), (1, 'Booking'), (2, 'Terjual')], default=0)),
            ],
            options={
                'db_table': 'kavling',
            },
        ),
    ]
