# Generated by Django 5.0.6 on 2024-06-18 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavling', '0002_kavling_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kavling',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
