# Generated by Django 5.0.6 on 2024-06-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_alter_transaksi_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='id_kavling',
            new_name='kavling',
        ),
    ]
