# Generated by Django 5.0.6 on 2024-09-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0005_cicilan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cicilan',
            table='cicilan',
        ),
    ]
