# Generated by Django 5.0.6 on 2024-09-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0007_cicilan_pembayaran_ke'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicilan',
            name='tanggal_pembayaran',
            field=models.DateField(null=True),
        ),
    ]
